{% set name = "pyelftools" %}
{% set version = "0.31" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyelftools-{{ version }}.tar.gz
  sha256: c774416b10310156879443b81187d182d8d9ee499660380e645918b50bc88f99

build:
  number: 1
  # noarch: python
  # this cannot be noarch b/c it has scripts
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools >=46.4.0
    - pip
  run:
    - python

test:
  imports:
    - elftools
    - elftools.common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eliben/pyelftools
  summary: Library for analyzing ELF files and DWARF debugging information
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
