{% set name = "pyelftools" %}
{% set version = "0.30" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyelftools-{{ version }}.tar.gz
  sha256: 2fc92b0d534f8b081f58c7c370967379123d8e00984deb53c209364efd575b40

build:
  number: 1
  # noarch: python
  # this cannot be noarch b/c it has scripts
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - setuptools >=46.4.0
    - pip
  run:
    - python

test:
  imports:
    - elftools
    - elftools.common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/eliben/pyelftools
  summary: Library for analyzing ELF files and DWARF debugging information
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
