{% set name = "pyelftools" %}
{% set version = "0.32" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyelftools-{{ version }}.tar.gz
  sha256: 6de90ee7b8263e740c8715a925382d4099b354f29ac48ea40d840cf7aa14ace5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  {{ python_min }}
    - setuptools >=46.4.0
    - pip
  run:
    - python >={{ python_min }}
    # different packages because of python scripts
    - __unix    # [unix]
    - __win     # [win]

test:
  imports:
    - elftools
    - elftools.common
  commands:
    - pip check
    - python   {{ python_min }}
  requires:
    - pip

about:
  home: https://github.com/eliben/pyelftools
  summary: Library for analyzing ELF files and DWARF debugging information
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - msarahan
    - ocefpaf
